/**
 * BASE TEMPLATE 2 — Universal CSV Export
 * Used by all raw data CSV exports. Consistent structure:
 * Row 1: Company Name, Row 2: Report Name, Row 3: Period, Row 4: Generated By
 * Row 5: blank, Row 6: Column Headers, Row 7+: Data
 */

export interface CsvColumnDef {
  key: string;
  label: string;
  format?: "text" | "date" | "datetime" | "decimal2" | "decimal3" | "decimal4" | "currency" | "percent" | "boolean" | "mono";
}

export interface CsvExportConfig {
  companyName: string;
  reportName: string;
  periodFrom?: string;
  periodTo?: string;
  generatedBy: { name: string; role: string };
  columns: CsvColumnDef[];
  data: Record<string, any>[];
}

function formatValue(value: any, format?: string): string {
  if (value === null || value === undefined) return "";
  switch (format) {
    case "date":
      return formatDate(value);
    case "datetime":
      return formatDateTime(value);
    case "decimal2":
      return Number(value).toFixed(2);
    case "decimal3":
      return Number(value).toFixed(3);
    case "decimal4":
      return Number(value).toFixed(4);
    case "currency":
      return Number(value).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
    case "percent":
      const num = Number(value);
      return `${num >= 0 ? "+" : ""}${num.toFixed(1)}%`;
    case "boolean":
      return value ? "Yes" : "No";
    default:
      return String(value);
  }
}

function formatDate(val: string): string {
  if (!val) return "";
  const d = new Date(val);
  if (isNaN(d.getTime())) return val;
  return `${String(d.getDate()).padStart(2, "0")}/${String(d.getMonth() + 1).padStart(2, "0")}/${d.getFullYear()}`;
}

function formatDateTime(val: string): string {
  if (!val) return "";
  const d = new Date(val);
  if (isNaN(d.getTime())) return val;
  return `${formatDate(val)} ${String(d.getHours()).padStart(2, "0")}:${String(d.getMinutes()).padStart(2, "0")}:${String(d.getSeconds()).padStart(2, "0")}`;
}

function escapeCsv(val: string): string {
  if (val.includes(",") || val.includes('"') || val.includes("\n")) {
    return `"${val.replace(/"/g, '""')}"`;
  }
  return val;
}

export function generateCsv(config: CsvExportConfig): string {
  const now = new Date();
  const lines: string[] = [];

  // Row 1: Company Name
  lines.push(escapeCsv(config.companyName));
  // Row 2: Report Name
  lines.push(escapeCsv(config.reportName));
  // Row 3: Period
  const period = config.periodFrom && config.periodTo
    ? `${formatDate(config.periodFrom)} to ${formatDate(config.periodTo)}`
    : "All Time";
  lines.push(escapeCsv(period));
  // Row 4: Generated By
  lines.push(escapeCsv(`${config.generatedBy.name} — ${config.generatedBy.role} — ${formatDateTime(now.toISOString())}`));
  // Row 5: Blank
  lines.push("");
  // Row 6: Column Headers
  lines.push(config.columns.map((c) => escapeCsv(c.label)).join(","));
  // Row 7+: Data
  for (const row of config.data) {
    lines.push(
      config.columns
        .map((col) => escapeCsv(formatValue(row[col.key], col.format)))
        .join(",")
    );
  }

  return lines.join("\n");
}

export function downloadCsv(config: CsvExportConfig, filename: string) {
  const csv = generateCsv(config);
  const blob = new Blob(["\uFEFF" + csv], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename.endsWith(".csv") ? filename : `${filename}.csv`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
