/**
 * TEMPLATE 5 — Payroll Summary PDF
 * Sensitive. Period-locked. Structured format.
 */
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export interface PayrollEmployee {
  fullName: string;
  jobTitle: string;
  employmentType: string;
  basicSalary: number;
  overtime: number;
  allowances: number;
  deductions: number;
  grossPay: number;
  tripBookouts: number;
  payeNote: string;
  nssaNote: string;
}

export interface PayrollPdfData {
  companyName: string;
  periodName: string;
  payDate?: string;
  isLocked: boolean;
  generatedBy: { name: string; role: string };
  totalGross: number;
  totalDeductions: number;
  totalNet: number;
  employeeCount: number;
  employees: PayrollEmployee[];
}

const NAVY: [number, number, number] = [13, 27, 46];
const ORANGE: [number, number, number] = [232, 101, 10];

function fmtCurrency(val: number): string {
  return val.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

export function generatePayrollPdf(data: PayrollPdfData): jsPDF {
  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
  const pw = doc.internal.pageSize.getWidth();
  const ph = doc.internal.pageSize.getHeight();
  const m = 15;
  let y = m;

  // Header
  doc.setFillColor(...NAVY);
  doc.rect(0, 0, pw, 25, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("PAYROLL SUMMARY", m, 12);
  doc.setFontSize(8);
  doc.text(data.companyName, pw - m, 10, { align: "right" });
  doc.setFontSize(7);
  doc.setFont("courier", "normal");
  doc.text(`Period: ${data.periodName}  |  Generated by: ${data.generatedBy.name}`, m, 20);
  if (data.isLocked) {
    doc.setFillColor(...ORANGE);
    doc.roundedRect(pw - m - 25, 14, 25, 7, 1, 1, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(7);
    doc.setFont("helvetica", "bold");
    doc.text("LOCKED", pw - m - 20, 19);
  }
  y = 30;

  // Summary
  const cards = [
    { label: "TOTAL GROSS", value: `$${fmtCurrency(data.totalGross)}` },
    { label: "TOTAL DEDUCTIONS", value: `$${fmtCurrency(data.totalDeductions)}` },
    { label: "TOTAL NET", value: `$${fmtCurrency(data.totalNet)}` },
    { label: "EMPLOYEES", value: String(data.employeeCount) },
  ];
  const cw = (pw - 2 * m - 12) / 4;
  cards.forEach((c, i) => {
    const cx = m + i * (cw + 4);
    doc.setFillColor(245, 245, 245);
    doc.rect(cx, y, cw, 14, "F");
    doc.setFillColor(...ORANGE);
    doc.rect(cx, y, cw, 1.5, "F");
    doc.setTextColor(100, 100, 100);
    doc.setFontSize(6);
    doc.setFont("helvetica", "normal");
    doc.text(c.label, cx + 3, y + 6);
    doc.setTextColor(...NAVY);
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text(c.value, cx + 3, y + 12);
  });
  y += 20;

  // Employee table
  autoTable(doc, {
    startY: y,
    head: [["Name", "Title", "Type", "Basic", "Overtime", "Allow.", "Deductions", "Gross", "Bookouts", "PAYE", "NSSA"]],
    body: data.employees.map((e) => [
      e.fullName, e.jobTitle, e.employmentType,
      fmtCurrency(e.basicSalary), fmtCurrency(e.overtime), fmtCurrency(e.allowances),
      fmtCurrency(e.deductions), fmtCurrency(e.grossPay), fmtCurrency(e.tripBookouts),
      e.payeNote, e.nssaNote,
    ]),
    margin: { left: m, right: m },
    styles: { fontSize: 6.5, cellPadding: 2 },
    headStyles: { fillColor: NAVY, textColor: [255, 255, 255], fontStyle: "bold", fontSize: 6 },
    columnStyles: { 3: { halign: "right" }, 4: { halign: "right" }, 5: { halign: "right" }, 6: { halign: "right" }, 7: { halign: "right" }, 8: { halign: "right" } },
  });

  y = (doc as any).lastAutoTable.finalY + 10;

  // Sign-off
  doc.setTextColor(...NAVY);
  doc.setFontSize(7);
  doc.setFont("helvetica", "normal");
  doc.text("Prepared by: ________________________", m, y);
  doc.text("Approved by: ________________________", m + 90, y);
  doc.text("Date: ________________________", m + 180, y);

  // Footer
  doc.setFontSize(6);
  doc.setTextColor(150, 150, 150);
  doc.setFont("courier", "normal");
  doc.text(`Generated by LynkFleet  |  ${data.companyName}  |  CONFIDENTIAL`, m, ph - 8);

  return doc;
}

export function downloadPayrollPdf(data: PayrollPdfData) {
  const doc = generatePayrollPdf(data);
  doc.save(`Payroll_${data.periodName.replace(/\s+/g, "_")}.pdf`);
}
