/**
 * BASE TEMPLATE 1 — Universal Report PDF
 * Used by all 63 report PDFs. Renders: header, summary cards, chart placeholder, data table, footer.
 */
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export interface ReportColumnDef {
  key: string;
  label: string;
  width?: number;
  align?: "left" | "center" | "right";
  mono?: boolean;
  format?: "text" | "date" | "datetime" | "decimal2" | "decimal3" | "decimal4" | "currency" | "percent" | "boolean";
}

export interface SummaryCard {
  label: string;
  value: string;
  unit?: string;
  state?: "neutral" | "good" | "warning" | "danger";
}

export interface ReportPdfConfig {
  reportName: string;
  module: string;
  companyName: string;
  companyLogoUrl?: string;
  periodFrom?: string;
  periodTo?: string;
  generatedBy: { name: string; role: string };
  summaryCards?: SummaryCard[];
  columns: ReportColumnDef[];
  data: Record<string, any>[];
}

function fmtDate(val: string): string {
  if (!val) return "";
  const d = new Date(val);
  if (isNaN(d.getTime())) return val;
  return `${String(d.getDate()).padStart(2, "0")}/${String(d.getMonth() + 1).padStart(2, "0")}/${d.getFullYear()}`;
}

function fmtDateTime(val: string): string {
  if (!val) return "";
  const d = new Date(val);
  if (isNaN(d.getTime())) return val;
  return `${fmtDate(val)} ${String(d.getHours()).padStart(2, "0")}:${String(d.getMinutes()).padStart(2, "0")}`;
}

function fmtVal(value: any, format?: string): string {
  if (value === null || value === undefined) return "—";
  switch (format) {
    case "date": return fmtDate(value);
    case "datetime": return fmtDateTime(value);
    case "decimal2": return Number(value).toFixed(2);
    case "decimal3": return Number(value).toFixed(3);
    case "decimal4": return Number(value).toFixed(4);
    case "currency": return Number(value).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
    case "percent": { const n = Number(value); return `${n >= 0 ? "+" : ""}${n.toFixed(1)}%`; }
    case "boolean": return value ? "Yes" : "No";
    default: return String(value);
  }
}

const NAVY = [13, 27, 46] as const;
const ORANGE = [232, 101, 10] as const;

export function generateReportPdf(config: ReportPdfConfig): jsPDF {
  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
  const pw = doc.internal.pageSize.getWidth();
  const ph = doc.internal.pageSize.getHeight();
  const margin = 15;
  let y = margin;

  // Header
  doc.setFillColor(...NAVY);
  doc.rect(0, 0, pw, 28, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(8);
  doc.text(config.companyName.toUpperCase(), pw - margin, 10, { align: "right" });
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text(config.reportName.toUpperCase(), margin, 14);
  doc.setFontSize(7);
  doc.setFont("courier", "normal");
  const now = new Date();
  const period = config.periodFrom && config.periodTo
    ? `${fmtDate(config.periodFrom)} to ${fmtDate(config.periodTo)}`
    : "All Time";
  doc.text(`Period: ${period}  |  Generated by: ${config.generatedBy.name} (${config.generatedBy.role})  |  ${fmtDateTime(now.toISOString())}`, margin, 22);
  y = 34;

  // Summary Cards
  if (config.summaryCards && config.summaryCards.length > 0) {
    const cardW = (pw - 2 * margin - (config.summaryCards.length - 1) * 4) / config.summaryCards.length;
    config.summaryCards.forEach((card, i) => {
      const cx = margin + i * (cardW + 4);
      doc.setFillColor(245, 245, 245);
      doc.rect(cx, y, cardW, 18, "F");
      const stateColor = card.state === "good" ? [34, 197, 94] : card.state === "warning" ? [245, 158, 11] : card.state === "danger" ? [239, 68, 68] : ORANGE;
      doc.setFillColor(...(stateColor as [number, number, number]));
      doc.rect(cx, y, cardW, 2, "F");
      doc.setTextColor(100, 100, 100);
      doc.setFontSize(6);
      doc.setFont("helvetica", "normal");
      doc.text(card.label.toUpperCase(), cx + 4, y + 8);
      doc.setTextColor(...NAVY);
      doc.setFontSize(12);
      doc.setFont("helvetica", "bold");
      doc.text(`${card.value}${card.unit ? ` ${card.unit}` : ""}`, cx + 4, y + 15);
    });
    y += 24;
  }

  // Data Table
  const head = [config.columns.map((c) => c.label)];
  const body = config.data.map((row) =>
    config.columns.map((col) => fmtVal(row[col.key], col.format))
  );

  autoTable(doc, {
    startY: y,
    head,
    body,
    margin: { left: margin, right: margin },
    styles: {
      fontSize: 7,
      cellPadding: 2,
      textColor: [30, 30, 30],
      lineColor: [220, 220, 220],
      lineWidth: 0.1,
    },
    headStyles: {
      fillColor: NAVY as unknown as [number, number, number],
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 7,
    },
    alternateRowStyles: {
      fillColor: [248, 248, 248],
    },
    columnStyles: config.columns.reduce((acc, col, i) => {
      acc[i] = {
        halign: col.align || "left",
        font: col.mono ? "courier" : "helvetica",
      };
      return acc;
    }, {} as Record<number, any>),
    didDrawPage: (data: any) => {
      // Footer on each page
      doc.setFontSize(6);
      doc.setTextColor(150, 150, 150);
      doc.setFont("courier", "normal");
      const pageNum = doc.getNumberOfPages();
      doc.text(`Generated by LynkFleet  |  ${config.companyName}  |  Page ${pageNum}`, margin, ph - 8);
    },
  });

  return doc;
}

export function downloadReportPdf(config: ReportPdfConfig, filename: string) {
  const doc = generateReportPdf(config);
  doc.save(filename.endsWith(".pdf") ? filename : `${filename}.pdf`);
}
