// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tyzcxeaqxmrmkdkijszq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5emN4ZWFxeG1ybWtka2lqc3pxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE1MTkxMzIsImV4cCI6MjA3NzA5NTEzMn0.dLnm0qODiuhDDKfTxPiSJONJbP7fLi6Xq57TcvhVTkU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});